impl mouse click
algon-320/toyterm pull request #5
Opened 2022-08-01 13:53 UTC by alphaKAI

Implement Mouse Tracking & SGR Extended Mouse Mode for enable handling mouse click.

2022-08-02 01:36 UTC, algon-320 requested changes

2022-08-02 01:36 UTC, algon-320 commented on src/terminal.rs
> +    pub mouse_track: bool,
名前に_modeみたいなサフィックスを入れておきたい

2022-08-02 01:36 UTC, algon-320 commented on src/terminal.rs
> +                        buf.mouse_track = true;
これは\e[?1000hの仕事

2022-08-02 01:36 UTC, algon-320 commented on src/window.rs
> +    pub fn sgr_mouse_report(&mut self, col: u32, row: u32, button: u8, state: &ElementState) {
pubじゃなくていいはず

2022-08-02 01:36 UTC, algon-320 commented on src/window.rs
> +    pub fn sgr_mouse_report(&mut self, col: u32, row: u32, button: u8, state: &ElementState) {
細かいけど、引数の順番は button, col, row に合わせた方がいいかも

2022-08-02 01:36 UTC, algon-320 commented on src/window.rs
> +        msg.push(32 + row as u8);
範囲外なら0を送るべき?

2022-08-02 01:36 UTC, algon-320 commented on src/window.rs
> +        let mut msg = vec![b'\x1b', b'[', b'M', 32 + button];
vecじゃなくてarrayでいいはず

2022-08-02 02:01 UTC, alphaKAI commented
@algon-320 修正しました。（コミット分けたほうがよかったかな。）

2022-08-02 03:34 UTC, algon-320 requested changes

2022-08-02 03:34 UTC, algon-320 commented on src/window.rs
> +                            if self.sgr_ext_mouse_track_mode {
SGRモードはレポートの形式を変えるためのモードであって、mouse trackモードが同時に有効になっていなければ送らないんだと思う

2022-08-02 03:34 UTC, algon-320 commented on src/window.rs
> +                        _ => 0, // FIXME: should be panic?
パニックするべきではなく、ログを書いて無視するべき？

2022-08-02 03:34 UTC, algon-320 commented on src/window.rs
> +        let msg = [b'\x1b', b'[', b'M', 32 + button, 32 + col, 32 + row];
範囲外のときは32ではなく0を送る

2022-08-02 03:34 UTC, algon-320 commented on src/window.rs
> +        let col = if col < cols { col } else { 0 } as u8;
範囲外というのはウィンドウサイズではなく、エンコードの制約(8bitに収まらなかったらとかそういう話)

2022-08-02 03:34 UTC, algon-320 commented on src/window.rs
> +                                self.sgr_ext_mouse_report(button + mods, col, row, state);
せっかくstateを変数で渡してるので、stateのmatchの外側に移してしまう方がシンプルになりそう

2022-08-02 03:39 UTC, algon-320 commented on src/window.rs
> +        let msg = [b'\x1b', b'[', b'M', 32 + button, 32 + col, 32 + row];
row, colとして取りうる値は1から223まで

2022-08-02 03:40 UTC, algon-320 commented on src/window.rs
> +        let col = if col < cols { col } else { 0 } as u8;
row, colとして取りうる値は1から223まで

2022-08-02 03:49 UTC, alphaKAI commented on src/window.rs
> +                            if self.sgr_ext_mouse_track_mode {
俺もそう思ってたんだけど、どうやら、NeoVim は 1006 しか送ってこないんだよなー。
なので、1006 をレポート形式を変えてマウストラックモードを enable という意味に解釈したほうがいいのでは？となった。

2022-08-02 03:50 UTC, alphaKAI commented on src/window.rs
> +                        _ => 0, // FIXME: should be panic?
OK, log::warn でログ書いておく。

2022-08-02 16:28 UTC, algon-320 requested changes

2022-08-02 16:28 UTC, algon-320 commented on src/terminal.rs
> +                    log::debug!("SM - ps : {:?}", ps);
log::trace!にしよう

2022-08-02 16:28 UTC, algon-320 commented on src/window.rs
> +    mouse_track_mode: bool,
bracketed_paste_mode の下辺りにまとめたい

2022-08-02 16:28 UTC, algon-320 commented on src/window.rs
> +                    let button = match state {
self.mouse.pressed_pos の更新と button を決める処理を分けたい

2022-08-02 16:28 UTC, algon-320 commented on src/window.rs
> +            .pty_write(&format!("\x1b[<{button};{col};{row}{m}").into_bytes());
as_bytesのほうがいい？

2022-08-02 16:32 UTC, algon-320 requested changes

2022-08-02 16:32 UTC, algon-320 commented on src/window.rs
> +            sgr_ext_mouse_track_mode: false,
ここもフィールドの順番を揃えたい

2022-08-03 02:25 UTC, alphaKAI commented
@algon-320 直したんで、レビューよろ！( `rustfmt_skip` の好みが分かれそう。)

2022-08-03 11:33 UTC, algon-320 requested changes

2022-08-03 11:33 UTC, algon-320 commented on src/window.rs
> +            sgr_ext_mouse_track_mode: false,
bracketed_paste_modeの下へ

2022-08-03 13:20 UTC, merged

2022-08-03 13:21 UTC, algon-320 commented
@alphaKAI ありがとう！